<?php

namespace AppBundle\Repository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    public function listCustomers() {

        $qb = $this->createQueryBuilder('c');
        $qb->select('c.id,c.address,c.email,c.cellPhone,c.fax,c.website')
            ->from('Customer', 'c');

        return $qb
            ->getQuery()
            ->getResult();
    }
}
