<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

    public function getInfo($id) {
        $qb = $this->createQueryBuilder('q');
        $qb->select('p.id,p.sellingPrice,p.tva')
            ->from('AppBundle:Product', 'p')
            ->innerJoin('p.tva','t')
            ->innerJoin('p.category', 'c')
            ->where('p.id= :id')
            ->setParameter('id', $id)
            ->setMaxResults(1);

        return $qb
            ->getQuery()
            ->getResult();
    }

}
