<?php

namespace AppBundle\Repository;

/**
 * ProductPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
