<?php

namespace AppBundle\Repository;

/**
 * PurchasePaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchasePaymentRepository extends \Doctrine\ORM\EntityRepository
{
}
