<?php

namespace AppBundle\Repository;

/**
 * PurchaseOrderDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseOrderDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
