<?php

namespace AppBundle\Repository;

/**
 * SalesPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesPaymentRepository extends \Doctrine\ORM\EntityRepository
{
}
