<?php

namespace AppBundle\Repository;

/**
 * SalesOrderDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesOrderDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
