<?php

namespace AppBundle\Repository;

/**
 * SalesOrderHeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesOrderHeaderRepository extends \Doctrine\ORM\EntityRepository
{

    public function getLastSalesOrderNumber()
    {
        $qb = $this->createQueryBuilder('s')
            ->select('s.id','s.salesOrderNumber')
            ->orderBy('s.id', 'DESC')
            ->setMaxResults(1);

        return  $qb->getQuery()->getResult();
    }

    public function confirmSales($id)
    {
        $qb = $this->createQueryBuilder('s')
            ->update('AppBundle\Entity\SalesOrderHeader', 's')
            ->set('s.status', 1)
            ->where('s.id = ?1')
            ->setParameter(1, $id);

        $qb->getQuery()->execute();
    }

    public function invoiceValidate($id)
    {
        $qb = $this->createQueryBuilder('s')
            ->update('AppBundle\Entity\SalesOrderHeader', 's')
            ->set('s.status', 2)
            ->where('s.id = ?1')
            ->setParameter(1, $id);

        $qb->getQuery()->execute();
    }

}
