<?php

namespace AppBundle\Repository;

/**
 * SupplierPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
