<?php

namespace AppBundle\Repository;

/**
 * TransactionHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
