app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user_profile_edit:
    path:      /account/profile
    defaults:  { _controller: FOSUserBundle:Profile:edit }

fos_user_registration_register:
    path:      /user/create
    defaults:  { _controller: FOSUserBundle:Registration:register }

fos_user_resetting_request:
    path:      /account/reset-password
    defaults:  { _controller: FOSUserBundle:Resetting:request }

fos_user_change_password:
    path:      /account/password
    defaults:  { _controller: FOSUserBundle:ChangePassword:changePassword }
